#
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include device/sony/common-treble/BoardConfigTreble.mk

PLATFORM_PATH := device/sony/yoshino

### BOARD
TARGET_BOARD_PLATFORM := msm8998
TARGET_BOARD_PLATFORM_GPU := qcom-adreno540

### PROCESSOR
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a73
TARGET_CPU_SMP := true

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a73

TARGET_USES_64_BIT_BINDER := true

ENABLE_CPUSETS := true

### KERNEL
TARGET_KERNEL_VERSION := 4.4
TARGET_KERNEL_SOURCE  := kernel/sony/msm8998

BOARD_KERNEL_CMDLINE += androidboot.bootdevice=1da4000.ufshc
BOARD_KERNEL_CMDLINE += display_status=on
BOARD_KERNEL_CMDLINE += lpm_levels.sleep_disabled=1

# See README_Xperia in Kernel source
BOARD_KERNEL_CMDLINE += user_debug=31
BOARD_KERNEL_CMDLINE += msm_rtb.filter=0x37
BOARD_KERNEL_CMDLINE += ehci-hcd.park=3
BOARD_KERNEL_CMDLINE += sched_enable_hmp=1
BOARD_KERNEL_CMDLINE += sched_enable_power_aware=1
BOARD_KERNEL_CMDLINE += service_locator.enable=1
BOARD_KERNEL_CMDLINE += zram.backend=z3fold
BOARD_KERNEL_CMDLINE += buildvariant=userdebug

# See README_Xperia in Kernel Source
BOARD_KERNEL_BASE        := 0x00000000
BOARD_KERNEL_PAGESIZE    := 4096
BOARD_RAMDISK_OFFSET     := 0x01000000

TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb

### PARTITIONS
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4

# Build vendor.img
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

# Build ext4 tools - system/vold
TARGET_USERIMAGES_USE_EXT4 := true

### DISPLAY
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024

### AUDIO
BOARD_SUPPORTS_QAHW := false
BOARD_SUPPORTS_SOUND_TRIGGER := true
BOARD_USES_SRS_TRUEMEDIA := false

AUDIO_FEATURE_ENABLED_3D_AUDIO := false # UNKNOWN
AUDIO_FEATURE_ENABLED_AAC_ADTS_OFFLOAD := true # STOCK
AUDIO_FEATURE_ENABLED_ACDB_LICENSE := false # STOCK
AUDIO_FEATURE_ENABLED_ALAC_OFFLOAD := true # STOCK
AUDIO_FEATURE_ENABLED_ANC_HEADSET := true # STOCK
AUDIO_FEATURE_ENABLED_APE_OFFLOAD := true # STOCK
AUDIO_FEATURE_ENABLED_AUDIOSPHERE := false # STOCK
AUDIO_FEATURE_ENABLED_COMPRESS_CAPTURE := false # STOCK
AUDIO_FEATURE_ENABLED_COMPRESS_VOIP := true # STOCK
AUDIO_FEATURE_ENABLED_CUSTOMSTEREO := true # STOCK
AUDIO_FEATURE_ENABLED_DEV_ARBI := false # STOCK
AUDIO_FEATURE_ENABLED_DISPLAY_PORT := true # STOCK
AUDIO_FEATURE_ENABLED_DS2_DOLBY_DAP := false # STOCK
AUDIO_FEATURE_ENABLED_DTS_EAGLE := false # STOCK
AUDIO_FEATURE_ENABLED_DYNAMIC_LOG := false # STOCK
AUDIO_FEATURE_ENABLED_EXTN_FLAC_DECODER := true
AUDIO_FEATURE_ENABLED_EXTN_FORMATS := true # STOCK
AUDIO_FEATURE_ENABLED_EXTN_RESAMPLER := false
AUDIO_FEATURE_ENABLED_FLAC_OFFLOAD := true # STOCK
AUDIO_FEATURE_ENABLED_FLUENCE := true # STOCK
AUDIO_FEATURE_ENABLED_FM_POWER_OPT := true # STOCK
AUDIO_FEATURE_ENABLED_GEF_SUPPORT := true # STOCK
AUDIO_FEATURE_ENABLED_HDMI_EDID := true # STOCK
AUDIO_FEATURE_ENABLED_HDMI_PASSTHROUGH := true # STOCK
AUDIO_FEATURE_ENABLED_HDMI_SPK := false # STOCK
AUDIO_FEATURE_ENABLED_HFP := true # STOCK
AUDIO_FEATURE_ENABLED_HIFI_AUDIO := false # STOCK
AUDIO_FEATURE_ENABLED_HW_ACCELERATED_EFFECTS := false
AUDIO_FEATURE_ENABLED_INCALL_MUSIC := false # STOCK
AUDIO_FEATURE_ENABLED_KPI_OPTIMIZE := true # STOCK
AUDIO_FEATURE_ENABLED_MULTI_VOICE_SESSIONS := true # STOCK
AUDIO_FEATURE_ENABLED_PCM_OFFLOAD := true # UNUSED
AUDIO_FEATURE_ENABLED_PCM_OFFLOAD_24 := true # UNUSED
AUDIO_FEATURE_ENABLED_PM_SUPPORT := false # STOCK
AUDIO_FEATURE_ENABLED_PROXY_DEVICE := true # STOCK
AUDIO_FEATURE_ENABLED_RAS := true # STOCK
AUDIO_FEATURE_ENABLED_SND_MONITOR := true # STOCK
AUDIO_FEATURE_ENABLED_SOURCE_TRACKING := true # STOCK
AUDIO_FEATURE_ENABLED_SPKR_PROTECTION := false # STOCK
AUDIO_FEATURE_ENABLED_SPLIT_A2DP := false # STOCK
AUDIO_FEATURE_ENABLED_SSR := false # STOCK = true
AUDIO_FEATURE_ENABLED_USB_TUNNEL_AUDIO := false # STOCK
AUDIO_FEATURE_ENABLED_VBAT_MONITOR := true # STOCK
AUDIO_FEATURE_ENABLED_VOICE_PRINT := false
AUDIO_FEATURE_ENABLED_VORBIS_OFFLOAD := true # STOCK
AUDIO_FEATURE_ENABLED_WMA_OFFLOAD := true # STOCK
AUDIO_FEATURE_ENABLED_KEEP_ALIVE := false # STOCK = true

AUDIO_USE_LL_AS_PRIMARY_OUTPUT := true # UNKNOWN

DOLBY_ENABLE := false
DTS_CODEC_M_ := false

MM_AUDIO_ENABLED_FTM := true
MM_AUDIO_ENABLED_SAFX := true

TARGET_USES_QCOM_MM_AUDIO := true

USE_CUSTOM_AUDIO_POLICY := 1
USE_LEGACY_AUDIO_DAEMON := false
USE_LEGACY_AUDIO_MEASUREMENT := false
USE_XML_AUDIO_POLICY_CONF := 1

### CAMERA
BOARD_QTI_CAMERA_32BIT_ONLY := true
TARGET_USES_MEDIA_EXTENSIONS := true
USE_DEVICE_SPECIFIC_CAMERA := true

### WIFI
BOARD_HAS_QCOM_WLAN := true
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_qcwcn
BOARD_WLAN_DEVICE := qcwcn
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_qcwcn
HOSTAPD_VERSION := VER_0_8_X
# This doesn't work because wifi driver is a background task
# we would need to wait till the fwpath is ready
# WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/wlan.ko"
# WIFI_DRIVER_MODULE_NAME := "wlan"
WIFI_DRIVER_FW_PATH_AP  := "ap"
WIFI_DRIVER_FW_PATH_P2P := "p2p"
WIFI_DRIVER_FW_PATH_STA := "sta"
WPA_SUPPLICANT_VERSION := VER_0_8_X

### BLUETOOTH
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(PLATFORM_PATH)/bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_QCOM := true
QCOM_BT_USE_BTNV := true
BOARD_HAS_QCA_BT_SIBS := true
WCNSS_FILTER_USES_SIBS := true

### RIL
TARGET_RIL_VARIANT := caf
TARGET_PER_MGR_ENABLED := true
PROTOBUF_SUPPORTED := true

### TIMESERVICE
BOARD_USES_QC_TIME_SERVICES := true

### HIDL
DEVICE_MANIFEST_FILE := $(PLATFORM_PATH)/manifest.xml
DEVICE_MATRIX_FILE := $(PLATFORM_PATH)/compatibility_matrix.xml

# vendor/qcom/opensource/cryptfs_hw
TARGET_HW_DISK_ENCRYPTION := true
TARGET_CRYPTFS_HW_PATH := vendor/qcom/opensource/cryptfs_hw

### SEPOLICY
BOARD_SEPOLICY_DIRS += device/sony/yoshino/sepolicy/vendor
BOARD_PLAT_PRIVATE_SEPOLICY_DIR += device/sony/yoshino/sepolicy/private

### RECOVERY
TARGET_RECOVERY_FSTAB := $(PLATFORM_PATH)/ramdisk/fstab.recovery

ifeq ($(WITH_TWRP),true)
-include $(PLATFORM_PATH)/twrp.mk
endif
